# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export EBD_BR
EBD_BR <- function(fathers, mothers) {
    .Call('_CAB2_EBD_BR', PACKAGE = 'CAB2', fathers, mothers)
}

#'@export EBD_RS_BR
EBD_RS_BR <- function(parents) {
    .Call('_CAB2_EBD_RS_BR', PACKAGE = 'CAB2', parents)
}

#'@export factorial_counts
factorial_counts <- function(event, break_labels, reset_labels, event_labels, max_breaks) {
    .Call('_CAB2_factorial_counts', PACKAGE = 'CAB2', event, break_labels, reset_labels, event_labels, max_breaks)
}

#'@export factorial_time_bin_2
factorial_time_bin_2 <- function(event, time, break_labels, reset_labels, event_labels, max_bin, bin_resolution, offset = 0) {
    .Call('_CAB2_factorial_time_bin_2', PACKAGE = 'CAB2', event, time, break_labels, reset_labels, event_labels, max_bin, bin_resolution, offset)
}

#'@export factorial_time_bin
factorial_time_bin <- function(event, time, break_labels, reset_labels, event_labels, max_bin, bin_resolution, offset = 0) {
    .Call('_CAB2_factorial_time_bin', PACKAGE = 'CAB2', event, time, break_labels, reset_labels, event_labels, max_bin, bin_resolution, offset)
}

#'@export int2bin
int2bin <- function(digits, integers) {
    .Call('_CAB2_int2bin', PACKAGE = 'CAB2', digits, integers)
}

#'@export ixyi
ixyi <- function(event, time, x_events, y_events, break_events) {
    .Call('_CAB2_ixyi', PACKAGE = 'CAB2', event, time, x_events, y_events, break_events)
}

#'@export ixyi_table_by_z
ixyi_table_by_z <- function(event, x_events, y_events, reset_labels, break_labels, bin_labels, max_bins) {
    .Call('_CAB2_ixyi_table_by_z', PACKAGE = 'CAB2', event, x_events, y_events, reset_labels, break_labels, bin_labels, max_bins)
}

#'@export ks
ks <- function(sample_1, sample_2) {
    .Call('_CAB2_ks', PACKAGE = 'CAB2', sample_1, sample_2)
}

rcpp_hello <- function() {
    .Call('_CAB2_rcpp_hello', PACKAGE = 'CAB2')
}

rcpparma_hello_world <- function() {
    .Call('_CAB2_rcpparma_hello_world', PACKAGE = 'CAB2')
}

rcpparma_outerproduct <- function(x) {
    .Call('_CAB2_rcpparma_outerproduct', PACKAGE = 'CAB2', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_CAB2_rcpparma_innerproduct', PACKAGE = 'CAB2', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_CAB2_rcpparma_bothproducts', PACKAGE = 'CAB2', x)
}

#'@export row_match
row_match <- function(mat, ref) {
    .Call('_CAB2_row_match', PACKAGE = 'CAB2', mat, ref)
}

#'@export row_match1
row_match1 <- function(mat, ref) {
    .Call('_CAB2_row_match1', PACKAGE = 'CAB2', mat, ref)
}

#'@export srs
srs <- function(choose_max, repeats, sample_size, replace) {
    .Call('_CAB2_srs', PACKAGE = 'CAB2', choose_max, repeats, sample_size, replace)
}

