# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export ixyi
#'@rdname ixyi
ixyi <- function(event, time, x_events, y_events, break_events) {
    .Call('_CAB2_ixyi', PACKAGE = 'CAB2', event, time, x_events, y_events, break_events)
}

rcpp_hello <- function() {
    .Call('_CAB2_rcpp_hello', PACKAGE = 'CAB2')
}

rcpparma_hello_world <- function() {
    .Call('_CAB2_rcpparma_hello_world', PACKAGE = 'CAB2')
}

rcpparma_outerproduct <- function(x) {
    .Call('_CAB2_rcpparma_outerproduct', PACKAGE = 'CAB2', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_CAB2_rcpparma_innerproduct', PACKAGE = 'CAB2', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_CAB2_rcpparma_bothproducts', PACKAGE = 'CAB2', x)
}

